-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  last_seen timestamp with time zone,
  is_online boolean default false,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for messages (Chat)
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender_id uuid references profiles(id) not null,
  receiver_id uuid references profiles(id) not null,
  content text,
  image_url text,
  seen_at timestamp with time zone,
  delivered_at timestamp with time zone,
  is_deleted boolean default false
);

alter table messages enable row level security;

create policy "Users can read messages sent to them or by them."
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

create policy "Users can send messages."
  on messages for insert
  with check ( auth.uid() = sender_id );

create policy "Users can update their own messages"
  on messages for update
  using ( auth.uid() = sender_id );

-- Create a table for follows
create table follows (
  follower_id uuid references profiles(id) not null,
  following_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (follower_id, following_id)
);

alter table follows enable row level security;

create policy "Follows are viewable by everyone."
  on follows for select
  using ( true );

create policy "Users can follow others."
  on follows for insert
  with check ( auth.uid() = follower_id );

create policy "Users can unfollow."
  on follows for delete
  using ( auth.uid() = follower_id );

-- Set up Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table follows;
alter publication supabase_realtime add table profiles;

-- Function to handle new user creation automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Storage Policies (Assuming bucket 'chat-images' exists)
-- You must create the bucket 'chat-images' in the Supabase Dashboard manually if it doesn't exist.

-- Allow public access to chat images
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'chat-images' );

-- Allow authenticated users to upload images
create policy "Authenticated users can upload"
  on storage.objects for insert
  with check ( bucket_id = 'chat-images' and auth.role() = 'authenticated' );
